// This file is generated by the 'node-soap-servicegenerator'
// visit : https://github.com/BreeeZe/node-soap-servicegenerator for more info

var NOT_IMPLEMENTED = {
  Fault: {
    Code: {
      Value: "soap:client"
    },
    Reason: {
      Text: "Method not implemented"
    }
  }
};

var MediaService = {
  MediaService : {
    Media : {
      //var GetServiceCapabilities = { };
      GetServiceCapabilities : function(args /*, cb, headers*/) {
        throw NOT_IMPLEMENTED;
        //var GetServiceCapabilitiesResponse = { 
          //Capabilities : { 
            //attributes : {
              //SnapshotUri : {xs:boolean},
              //Rotation : {xs:boolean},
              //VideoSourceMode : {xs:boolean},
              //OSD : {xs:boolean}
            //},
            //ProfileCapabilities : { 
              //attributes : {
                //MaximumNumberOfProfiles : {xs:int}
              //}},
            //StreamingCapabilities : { 
              //attributes : {
                //RTPMulticast : {xs:boolean},
                //RTP_TCP : {xs:boolean},
                //RTP_RTSP_TCP : {xs:boolean},
                //NonAggregateControl : {xs:boolean},
                //NoRTSPStreaming : {xs:boolean}
              //}}
          //}
        //
        //};
        //return GetServiceCapabilitiesResponse;
      },

      //var GetVideoSources = { };
      GetVideoSources : function(args /*, cb, headers*/) {
        throw NOT_IMPLEMENTED;
        //var GetVideoSourcesResponse = { 
          //VideoSources : { 

            //attributes : {
              //token : {tt:ReferenceToken}
            //}
          //}
        //
        //};
        //return GetVideoSourcesResponse;
      },

      //var GetAudioSources = { };
      GetAudioSources : function(args /*, cb, headers*/) {
        throw NOT_IMPLEMENTED;
        //var GetAudioSourcesResponse = { 
          //AudioSources : { 

            //attributes : {
              //token : {tt:ReferenceToken}
            //}
          //}
        //
        //};
        //return GetAudioSourcesResponse;
      },

      //var GetAudioOutputs = { };
      GetAudioOutputs : function(args /*, cb, headers*/) {
        throw NOT_IMPLEMENTED;
        //var GetAudioOutputsResponse = { 
          //AudioOutputs : { 

            //attributes : {
              //token : {tt:ReferenceToken}
            //}
          //}
        //
        //};
        //return GetAudioOutputsResponse;
      },

      //var CreateProfile = { 
        //Name : { xs:string},
        //Token : { xs:string}
      //
      //};
      CreateProfile : function(args /*, cb, headers*/) {
        throw NOT_IMPLEMENTED;
        //var CreateProfileResponse = { 
          //Profile : { 
            //attributes : {
              //token : {tt:ReferenceToken},
              //fixed : {xs:boolean}
            //},
            //Name : { xs:string},
            //VideoSourceConfiguration : { 

              //attributes : {
                //token : {tt:ReferenceToken}
              //},
              //Name : { xs:string},
              //UseCount : { xs:int}
            //
            //},
            //AudioSourceConfiguration : { 

              //attributes : {
                //token : {tt:ReferenceToken}
              //},
              //Name : { xs:string},
              //UseCount : { xs:int}
            //
            //},
            //VideoEncoderConfiguration : { 

              //attributes : {
                //token : {tt:ReferenceToken}
              //},
              //Name : { xs:string},
              //UseCount : { xs:int}
            //
            //},
            //AudioEncoderConfiguration : { 

              //attributes : {
                //token : {tt:ReferenceToken}
              //},
              //Name : { xs:string},
              //UseCount : { xs:int}
            //
            //},
            //VideoAnalyticsConfiguration : { 

              //attributes : {
                //token : {tt:ReferenceToken}
              //},
              //Name : { xs:string},
              //UseCount : { xs:int}
            //
            //},
            //PTZConfiguration : { 

              //attributes : {
                //token : {tt:ReferenceToken}
              //},
              //Name : { xs:string},
              //UseCount : { xs:int}
            //
            //},
            //MetadataConfiguration : { 

              //attributes : {
                //token : {tt:ReferenceToken}
              //},
              //Name : { xs:string},
              //UseCount : { xs:int}
            //
            //},
            //Extension : { 
              //AudioOutputConfiguration : { 

                //attributes : {
                  //token : {tt:ReferenceToken}
                //},
                //Name : { xs:string},
                //UseCount : { xs:int}
              //
              //},
              //AudioDecoderConfiguration : { 

                //attributes : {
                  //token : {tt:ReferenceToken}
                //},
                //Name : { xs:string},
                //UseCount : { xs:int}
              //
              //},
              //Extension : { }
            //}
          //}
        //
        //};
        //return CreateProfileResponse;
      },

      //var GetProfile = { 
        //ProfileToken : { xs:string}
      //
      //};
      GetProfile : function(args /*, cb, headers*/) {
        throw NOT_IMPLEMENTED;
        //var GetProfileResponse = { 
          //Profile : { 
            //attributes : {
              //token : {tt:ReferenceToken},
              //fixed : {xs:boolean}
            //},
            //Name : { xs:string},
            //VideoSourceConfiguration : { 

              //attributes : {
                //token : {tt:ReferenceToken}
              //},
              //Name : { xs:string},
              //UseCount : { xs:int}
            //
            //},
            //AudioSourceConfiguration : { 

              //attributes : {
                //token : {tt:ReferenceToken}
              //},
              //Name : { xs:string},
              //UseCount : { xs:int}
            //
            //},
            //VideoEncoderConfiguration : { 

              //attributes : {
                //token : {tt:ReferenceToken}
              //},
              //Name : { xs:string},
              //UseCount : { xs:int}
            //
            //},
            //AudioEncoderConfiguration : { 

              //attributes : {
                //token : {tt:ReferenceToken}
              //},
              //Name : { xs:string},
              //UseCount : { xs:int}
            //
            //},
            //VideoAnalyticsConfiguration : { 

              //attributes : {
                //token : {tt:ReferenceToken}
              //},
              //Name : { xs:string},
              //UseCount : { xs:int}
            //
            //},
            //PTZConfiguration : { 

              //attributes : {
                //token : {tt:ReferenceToken}
              //},
              //Name : { xs:string},
              //UseCount : { xs:int}
            //
            //},
            //MetadataConfiguration : { 

              //attributes : {
                //token : {tt:ReferenceToken}
              //},
              //Name : { xs:string},
              //UseCount : { xs:int}
            //
            //},
            //Extension : { 
              //AudioOutputConfiguration : { 

                //attributes : {
                  //token : {tt:ReferenceToken}
                //},
                //Name : { xs:string},
                //UseCount : { xs:int}
              //
              //},
              //AudioDecoderConfiguration : { 

                //attributes : {
                  //token : {tt:ReferenceToken}
                //},
                //Name : { xs:string},
                //UseCount : { xs:int}
              //
              //},
              //Extension : { }
            //}
          //}
        //
        //};
        //return GetProfileResponse;
      },

      //var GetProfiles = { };
      GetProfiles : function(args /*, cb, headers*/) {
        throw NOT_IMPLEMENTED;
        //var GetProfilesResponse = { 
          //Profiles : { 
            //attributes : {
              //token : {tt:ReferenceToken},
              //fixed : {xs:boolean}
            //},
            //Name : { xs:string},
            //VideoSourceConfiguration : { 

              //attributes : {
                //token : {tt:ReferenceToken}
              //},
              //Name : { xs:string},
              //UseCount : { xs:int}
            //
            //},
            //AudioSourceConfiguration : { 

              //attributes : {
                //token : {tt:ReferenceToken}
              //},
              //Name : { xs:string},
              //UseCount : { xs:int}
            //
            //},
            //VideoEncoderConfiguration : { 

              //attributes : {
                //token : {tt:ReferenceToken}
              //},
              //Name : { xs:string},
              //UseCount : { xs:int}
            //
            //},
            //AudioEncoderConfiguration : { 

              //attributes : {
                //token : {tt:ReferenceToken}
              //},
              //Name : { xs:string},
              //UseCount : { xs:int}
            //
            //},
            //VideoAnalyticsConfiguration : { 

              //attributes : {
                //token : {tt:ReferenceToken}
              //},
              //Name : { xs:string},
              //UseCount : { xs:int}
            //
            //},
            //PTZConfiguration : { 

              //attributes : {
                //token : {tt:ReferenceToken}
              //},
              //Name : { xs:string},
              //UseCount : { xs:int}
            //
            //},
            //MetadataConfiguration : { 

              //attributes : {
                //token : {tt:ReferenceToken}
              //},
              //Name : { xs:string},
              //UseCount : { xs:int}
            //
            //},
            //Extension : { 
              //AudioOutputConfiguration : { 

                //attributes : {
                  //token : {tt:ReferenceToken}
                //},
                //Name : { xs:string},
                //UseCount : { xs:int}
              //
              //},
              //AudioDecoderConfiguration : { 

                //attributes : {
                  //token : {tt:ReferenceToken}
                //},
                //Name : { xs:string},
                //UseCount : { xs:int}
              //
              //},
              //Extension : { }
            //}
          //}
        //
        //};
        //return GetProfilesResponse;
      },

      //var AddVideoEncoderConfiguration = { 
        //ProfileToken : { xs:string},
        //ConfigurationToken : { xs:string}
      //
      //};
      AddVideoEncoderConfiguration : function(args /*, cb, headers*/) {
        throw NOT_IMPLEMENTED;
        //var AddVideoEncoderConfigurationResponse = { };
        //return AddVideoEncoderConfigurationResponse;
      },

      //var RemoveVideoEncoderConfiguration = { 
        //ProfileToken : { xs:string}
      //
      //};
      RemoveVideoEncoderConfiguration : function(args /*, cb, headers*/) {
        throw NOT_IMPLEMENTED;
        //var RemoveVideoEncoderConfigurationResponse = { };
        //return RemoveVideoEncoderConfigurationResponse;
      },

      //var AddVideoSourceConfiguration = { 
        //ProfileToken : { xs:string},
        //ConfigurationToken : { xs:string}
      //
      //};
      AddVideoSourceConfiguration : function(args /*, cb, headers*/) {
        throw NOT_IMPLEMENTED;
        //var AddVideoSourceConfigurationResponse = { };
        //return AddVideoSourceConfigurationResponse;
      },

      //var RemoveVideoSourceConfiguration = { 
        //ProfileToken : { xs:string}
      //
      //};
      RemoveVideoSourceConfiguration : function(args /*, cb, headers*/) {
        throw NOT_IMPLEMENTED;
        //var RemoveVideoSourceConfigurationResponse = { };
        //return RemoveVideoSourceConfigurationResponse;
      },

      //var AddAudioEncoderConfiguration = { 
        //ProfileToken : { xs:string},
        //ConfigurationToken : { xs:string}
      //
      //};
      AddAudioEncoderConfiguration : function(args /*, cb, headers*/) {
        throw NOT_IMPLEMENTED;
        //var AddAudioEncoderConfigurationResponse = { };
        //return AddAudioEncoderConfigurationResponse;
      },

      //var RemoveAudioEncoderConfiguration = { 
        //ProfileToken : { xs:string}
      //
      //};
      RemoveAudioEncoderConfiguration : function(args /*, cb, headers*/) {
        throw NOT_IMPLEMENTED;
        //var RemoveAudioEncoderConfigurationResponse = { };
        //return RemoveAudioEncoderConfigurationResponse;
      },

      //var AddAudioSourceConfiguration = { 
        //ProfileToken : { xs:string},
        //ConfigurationToken : { xs:string}
      //
      //};
      AddAudioSourceConfiguration : function(args /*, cb, headers*/) {
        throw NOT_IMPLEMENTED;
        //var AddAudioSourceConfigurationResponse = { };
        //return AddAudioSourceConfigurationResponse;
      },

      //var RemoveAudioSourceConfiguration = { 
        //ProfileToken : { xs:string}
      //
      //};
      RemoveAudioSourceConfiguration : function(args /*, cb, headers*/) {
        throw NOT_IMPLEMENTED;
        //var RemoveAudioSourceConfigurationResponse = { };
        //return RemoveAudioSourceConfigurationResponse;
      },

      //var AddPTZConfiguration = { 
        //ProfileToken : { xs:string},
        //ConfigurationToken : { xs:string}
      //
      //};
      AddPTZConfiguration : function(args /*, cb, headers*/) {
        throw NOT_IMPLEMENTED;
        //var AddPTZConfigurationResponse = { };
        //return AddPTZConfigurationResponse;
      },

      //var RemovePTZConfiguration = { 
        //ProfileToken : { xs:string}
      //
      //};
      RemovePTZConfiguration : function(args /*, cb, headers*/) {
        throw NOT_IMPLEMENTED;
        //var RemovePTZConfigurationResponse = { };
        //return RemovePTZConfigurationResponse;
      },

      //var AddVideoAnalyticsConfiguration = { 
        //ProfileToken : { xs:string},
        //ConfigurationToken : { xs:string}
      //
      //};
      AddVideoAnalyticsConfiguration : function(args /*, cb, headers*/) {
        throw NOT_IMPLEMENTED;
        //var AddVideoAnalyticsConfigurationResponse = { };
        //return AddVideoAnalyticsConfigurationResponse;
      },

      //var RemoveVideoAnalyticsConfiguration = { 
        //ProfileToken : { xs:string}
      //
      //};
      RemoveVideoAnalyticsConfiguration : function(args /*, cb, headers*/) {
        throw NOT_IMPLEMENTED;
        //var RemoveVideoAnalyticsConfigurationResponse = { };
        //return RemoveVideoAnalyticsConfigurationResponse;
      },

      //var AddMetadataConfiguration = { 
        //ProfileToken : { xs:string},
        //ConfigurationToken : { xs:string}
      //
      //};
      AddMetadataConfiguration : function(args /*, cb, headers*/) {
        throw NOT_IMPLEMENTED;
        //var AddMetadataConfigurationResponse = { };
        //return AddMetadataConfigurationResponse;
      },

      //var RemoveMetadataConfiguration = { 
        //ProfileToken : { xs:string}
      //
      //};
      RemoveMetadataConfiguration : function(args /*, cb, headers*/) {
        throw NOT_IMPLEMENTED;
        //var RemoveMetadataConfigurationResponse = { };
        //return RemoveMetadataConfigurationResponse;
      },

      //var AddAudioOutputConfiguration = { 
        //ProfileToken : { xs:string},
        //ConfigurationToken : { xs:string}
      //
      //};
      AddAudioOutputConfiguration : function(args /*, cb, headers*/) {
        throw NOT_IMPLEMENTED;
        //var AddAudioOutputConfigurationResponse = { };
        //return AddAudioOutputConfigurationResponse;
      },

      //var RemoveAudioOutputConfiguration = { 
        //ProfileToken : { xs:string}
      //
      //};
      RemoveAudioOutputConfiguration : function(args /*, cb, headers*/) {
        throw NOT_IMPLEMENTED;
        //var RemoveAudioOutputConfigurationResponse = { };
        //return RemoveAudioOutputConfigurationResponse;
      },

      //var AddAudioDecoderConfiguration = { 
        //ProfileToken : { xs:string},
        //ConfigurationToken : { xs:string}
      //
      //};
      AddAudioDecoderConfiguration : function(args /*, cb, headers*/) {
        throw NOT_IMPLEMENTED;
        //var AddAudioDecoderConfigurationResponse = { };
        //return AddAudioDecoderConfigurationResponse;
      },

      //var RemoveAudioDecoderConfiguration = { 
        //ProfileToken : { xs:string}
      //
      //};
      RemoveAudioDecoderConfiguration : function(args /*, cb, headers*/) {
        throw NOT_IMPLEMENTED;
        //var RemoveAudioDecoderConfigurationResponse = { };
        //return RemoveAudioDecoderConfigurationResponse;
      },

      //var DeleteProfile = { 
        //ProfileToken : { xs:string}
      //
      //};
      DeleteProfile : function(args /*, cb, headers*/) {
        throw NOT_IMPLEMENTED;
        //var DeleteProfileResponse = { };
        //return DeleteProfileResponse;
      },

      //var GetVideoSourceConfigurations = { };
      GetVideoSourceConfigurations : function(args /*, cb, headers*/) {
        throw NOT_IMPLEMENTED;
        //var GetVideoSourceConfigurationsResponse = { 
          //Configurations : { 

            //attributes : {
              //token : {tt:ReferenceToken}
            //},
            //Name : { xs:string},
            //UseCount : { xs:int}
          //
          //}
        //
        //};
        //return GetVideoSourceConfigurationsResponse;
      },

      //var GetVideoEncoderConfigurations = { };
      GetVideoEncoderConfigurations : function(args /*, cb, headers*/) {
        throw NOT_IMPLEMENTED;
        //var GetVideoEncoderConfigurationsResponse = { 
          //Configurations : { 

            //attributes : {
              //token : {tt:ReferenceToken}
            //},
            //Name : { xs:string},
            //UseCount : { xs:int}
          //
          //}
        //
        //};
        //return GetVideoEncoderConfigurationsResponse;
      },

      //var GetAudioSourceConfigurations = { };
      GetAudioSourceConfigurations : function(args /*, cb, headers*/) {
        throw NOT_IMPLEMENTED;
        //var GetAudioSourceConfigurationsResponse = { 
          //Configurations : { 

            //attributes : {
              //token : {tt:ReferenceToken}
            //},
            //Name : { xs:string},
            //UseCount : { xs:int}
          //
          //}
        //
        //};
        //return GetAudioSourceConfigurationsResponse;
      },

      //var GetAudioEncoderConfigurations = { };
      GetAudioEncoderConfigurations : function(args /*, cb, headers*/) {
        throw NOT_IMPLEMENTED;
        //var GetAudioEncoderConfigurationsResponse = { 
          //Configurations : { 

            //attributes : {
              //token : {tt:ReferenceToken}
            //},
            //Name : { xs:string},
            //UseCount : { xs:int}
          //
          //}
        //
        //};
        //return GetAudioEncoderConfigurationsResponse;
      },

      //var GetVideoAnalyticsConfigurations = { };
      GetVideoAnalyticsConfigurations : function(args /*, cb, headers*/) {
        throw NOT_IMPLEMENTED;
        //var GetVideoAnalyticsConfigurationsResponse = { 
          //Configurations : { 

            //attributes : {
              //token : {tt:ReferenceToken}
            //},
            //Name : { xs:string},
            //UseCount : { xs:int}
          //
          //}
        //
        //};
        //return GetVideoAnalyticsConfigurationsResponse;
      },

      //var GetMetadataConfigurations = { };
      GetMetadataConfigurations : function(args /*, cb, headers*/) {
        throw NOT_IMPLEMENTED;
        //var GetMetadataConfigurationsResponse = { 
          //Configurations : { 

            //attributes : {
              //token : {tt:ReferenceToken}
            //},
            //Name : { xs:string},
            //UseCount : { xs:int}
          //
          //}
        //
        //};
        //return GetMetadataConfigurationsResponse;
      },

      //var GetAudioOutputConfigurations = { };
      GetAudioOutputConfigurations : function(args /*, cb, headers*/) {
        throw NOT_IMPLEMENTED;
        //var GetAudioOutputConfigurationsResponse = { 
          //Configurations : { 

            //attributes : {
              //token : {tt:ReferenceToken}
            //},
            //Name : { xs:string},
            //UseCount : { xs:int}
          //
          //}
        //
        //};
        //return GetAudioOutputConfigurationsResponse;
      },

      //var GetAudioDecoderConfigurations = { };
      GetAudioDecoderConfigurations : function(args /*, cb, headers*/) {
        throw NOT_IMPLEMENTED;
        //var GetAudioDecoderConfigurationsResponse = { 
          //Configurations : { 

            //attributes : {
              //token : {tt:ReferenceToken}
            //},
            //Name : { xs:string},
            //UseCount : { xs:int}
          //
          //}
        //
        //};
        //return GetAudioDecoderConfigurationsResponse;
      },

      //var GetVideoSourceConfiguration = { 
        //ConfigurationToken : { xs:string}
      //
      //};
      GetVideoSourceConfiguration : function(args /*, cb, headers*/) {
        throw NOT_IMPLEMENTED;
        //var GetVideoSourceConfigurationResponse = { 
          //Configuration : { 

            //attributes : {
              //token : {tt:ReferenceToken}
            //},
            //Name : { xs:string},
            //UseCount : { xs:int}
          //
          //}
        //
        //};
        //return GetVideoSourceConfigurationResponse;
      },

      //var GetVideoEncoderConfiguration = { 
        //ConfigurationToken : { xs:string}
      //
      //};
      GetVideoEncoderConfiguration : function(args /*, cb, headers*/) {
        throw NOT_IMPLEMENTED;
        //var GetVideoEncoderConfigurationResponse = { 
          //Configuration : { 

            //attributes : {
              //token : {tt:ReferenceToken}
            //},
            //Name : { xs:string},
            //UseCount : { xs:int}
          //
          //}
        //
        //};
        //return GetVideoEncoderConfigurationResponse;
      },

      //var GetAudioSourceConfiguration = { 
        //ConfigurationToken : { xs:string}
      //
      //};
      GetAudioSourceConfiguration : function(args /*, cb, headers*/) {
        throw NOT_IMPLEMENTED;
        //var GetAudioSourceConfigurationResponse = { 
          //Configuration : { 

            //attributes : {
              //token : {tt:ReferenceToken}
            //},
            //Name : { xs:string},
            //UseCount : { xs:int}
          //
          //}
        //
        //};
        //return GetAudioSourceConfigurationResponse;
      },

      //var GetAudioEncoderConfiguration = { 
        //ConfigurationToken : { xs:string}
      //
      //};
      GetAudioEncoderConfiguration : function(args /*, cb, headers*/) {
        throw NOT_IMPLEMENTED;
        //var GetAudioEncoderConfigurationResponse = { 
          //Configuration : { 

            //attributes : {
              //token : {tt:ReferenceToken}
            //},
            //Name : { xs:string},
            //UseCount : { xs:int}
          //
          //}
        //
        //};
        //return GetAudioEncoderConfigurationResponse;
      },

      //var GetVideoAnalyticsConfiguration = { 
        //ConfigurationToken : { xs:string}
      //
      //};
      GetVideoAnalyticsConfiguration : function(args /*, cb, headers*/) {
        throw NOT_IMPLEMENTED;
        //var GetVideoAnalyticsConfigurationResponse = { 
          //Configuration : { 

            //attributes : {
              //token : {tt:ReferenceToken}
            //},
            //Name : { xs:string},
            //UseCount : { xs:int}
          //
          //}
        //
        //};
        //return GetVideoAnalyticsConfigurationResponse;
      },

      //var GetMetadataConfiguration = { 
        //ConfigurationToken : { xs:string}
      //
      //};
      GetMetadataConfiguration : function(args /*, cb, headers*/) {
        throw NOT_IMPLEMENTED;
        //var GetMetadataConfigurationResponse = { 
          //Configuration : { 

            //attributes : {
              //token : {tt:ReferenceToken}
            //},
            //Name : { xs:string},
            //UseCount : { xs:int}
          //
          //}
        //
        //};
        //return GetMetadataConfigurationResponse;
      },

      //var GetAudioOutputConfiguration = { 
        //ConfigurationToken : { xs:string}
      //
      //};
      GetAudioOutputConfiguration : function(args /*, cb, headers*/) {
        throw NOT_IMPLEMENTED;
        //var GetAudioOutputConfigurationResponse = { 
          //Configuration : { 

            //attributes : {
              //token : {tt:ReferenceToken}
            //},
            //Name : { xs:string},
            //UseCount : { xs:int}
          //
          //}
        //
        //};
        //return GetAudioOutputConfigurationResponse;
      },

      //var GetAudioDecoderConfiguration = { 
        //ConfigurationToken : { xs:string}
      //
      //};
      GetAudioDecoderConfiguration : function(args /*, cb, headers*/) {
        throw NOT_IMPLEMENTED;
        //var GetAudioDecoderConfigurationResponse = { 
          //Configuration : { 

            //attributes : {
              //token : {tt:ReferenceToken}
            //},
            //Name : { xs:string},
            //UseCount : { xs:int}
          //
          //}
        //
        //};
        //return GetAudioDecoderConfigurationResponse;
      },

      //var GetCompatibleVideoEncoderConfigurations = { 
        //ProfileToken : { xs:string}
      //
      //};
      GetCompatibleVideoEncoderConfigurations : function(args /*, cb, headers*/) {
        throw NOT_IMPLEMENTED;
        //var GetCompatibleVideoEncoderConfigurationsResponse = { 
          //Configurations : { 

            //attributes : {
              //token : {tt:ReferenceToken}
            //},
            //Name : { xs:string},
            //UseCount : { xs:int}
          //
          //}
        //
        //};
        //return GetCompatibleVideoEncoderConfigurationsResponse;
      },

      //var GetCompatibleVideoSourceConfigurations = { 
        //ProfileToken : { xs:string}
      //
      //};
      GetCompatibleVideoSourceConfigurations : function(args /*, cb, headers*/) {
        throw NOT_IMPLEMENTED;
        //var GetCompatibleVideoSourceConfigurationsResponse = { 
          //Configurations : { 

            //attributes : {
              //token : {tt:ReferenceToken}
            //},
            //Name : { xs:string},
            //UseCount : { xs:int}
          //
          //}
        //
        //};
        //return GetCompatibleVideoSourceConfigurationsResponse;
      },

      //var GetCompatibleAudioEncoderConfigurations = { 
        //ProfileToken : { xs:string}
      //
      //};
      GetCompatibleAudioEncoderConfigurations : function(args /*, cb, headers*/) {
        throw NOT_IMPLEMENTED;
        //var GetCompatibleAudioEncoderConfigurationsResponse = { 
          //Configurations : { 

            //attributes : {
              //token : {tt:ReferenceToken}
            //},
            //Name : { xs:string},
            //UseCount : { xs:int}
          //
          //}
        //
        //};
        //return GetCompatibleAudioEncoderConfigurationsResponse;
      },

      //var GetCompatibleAudioSourceConfigurations = { 
        //ProfileToken : { xs:string}
      //
      //};
      GetCompatibleAudioSourceConfigurations : function(args /*, cb, headers*/) {
        throw NOT_IMPLEMENTED;
        //var GetCompatibleAudioSourceConfigurationsResponse = { 
          //Configurations : { 

            //attributes : {
              //token : {tt:ReferenceToken}
            //},
            //Name : { xs:string},
            //UseCount : { xs:int}
          //
          //}
        //
        //};
        //return GetCompatibleAudioSourceConfigurationsResponse;
      },

      //var GetCompatibleVideoAnalyticsConfigurations = { 
        //ProfileToken : { xs:string}
      //
      //};
      GetCompatibleVideoAnalyticsConfigurations : function(args /*, cb, headers*/) {
        throw NOT_IMPLEMENTED;
        //var GetCompatibleVideoAnalyticsConfigurationsResponse = { 
          //Configurations : { 

            //attributes : {
              //token : {tt:ReferenceToken}
            //},
            //Name : { xs:string},
            //UseCount : { xs:int}
          //
          //}
        //
        //};
        //return GetCompatibleVideoAnalyticsConfigurationsResponse;
      },

      //var GetCompatibleMetadataConfigurations = { 
        //ProfileToken : { xs:string}
      //
      //};
      GetCompatibleMetadataConfigurations : function(args /*, cb, headers*/) {
        throw NOT_IMPLEMENTED;
        //var GetCompatibleMetadataConfigurationsResponse = { 
          //Configurations : { 

            //attributes : {
              //token : {tt:ReferenceToken}
            //},
            //Name : { xs:string},
            //UseCount : { xs:int}
          //
          //}
        //
        //};
        //return GetCompatibleMetadataConfigurationsResponse;
      },

      //var GetCompatibleAudioOutputConfigurations = { 
        //ProfileToken : { xs:string}
      //
      //};
      GetCompatibleAudioOutputConfigurations : function(args /*, cb, headers*/) {
        throw NOT_IMPLEMENTED;
        //var GetCompatibleAudioOutputConfigurationsResponse = { 
          //Configurations : { 

            //attributes : {
              //token : {tt:ReferenceToken}
            //},
            //Name : { xs:string},
            //UseCount : { xs:int}
          //
          //}
        //
        //};
        //return GetCompatibleAudioOutputConfigurationsResponse;
      },

      //var GetCompatibleAudioDecoderConfigurations = { 
        //ProfileToken : { xs:string}
      //
      //};
      GetCompatibleAudioDecoderConfigurations : function(args /*, cb, headers*/) {
        throw NOT_IMPLEMENTED;
        //var GetCompatibleAudioDecoderConfigurationsResponse = { 
          //Configurations : { 

            //attributes : {
              //token : {tt:ReferenceToken}
            //},
            //Name : { xs:string},
            //UseCount : { xs:int}
          //
          //}
        //
        //};
        //return GetCompatibleAudioDecoderConfigurationsResponse;
      },

      //var SetVideoSourceConfiguration = { 
        //Configuration : { 

          //attributes : {
            //token : {tt:ReferenceToken}
          //},
          //Name : { xs:string},
          //UseCount : { xs:int}
        //
        //},
        //ForcePersistence : { xs:boolean}
      //
      //};
      SetVideoSourceConfiguration : function(args /*, cb, headers*/) {
        throw NOT_IMPLEMENTED;
        //var SetVideoSourceConfigurationResponse = { };
        //return SetVideoSourceConfigurationResponse;
      },

      //var SetVideoEncoderConfiguration = { 
        //Configuration : { 

          //attributes : {
            //token : {tt:ReferenceToken}
          //},
          //Name : { xs:string},
          //UseCount : { xs:int}
        //
        //},
        //ForcePersistence : { xs:boolean}
      //
      //};
      SetVideoEncoderConfiguration : function(args /*, cb, headers*/) {
        throw NOT_IMPLEMENTED;
        //var SetVideoEncoderConfigurationResponse = { };
        //return SetVideoEncoderConfigurationResponse;
      },

      //var SetAudioSourceConfiguration = { 
        //Configuration : { 

          //attributes : {
            //token : {tt:ReferenceToken}
          //},
          //Name : { xs:string},
          //UseCount : { xs:int}
        //
        //},
        //ForcePersistence : { xs:boolean}
      //
      //};
      SetAudioSourceConfiguration : function(args /*, cb, headers*/) {
        throw NOT_IMPLEMENTED;
        //var SetAudioSourceConfigurationResponse = { };
        //return SetAudioSourceConfigurationResponse;
      },

      //var SetAudioEncoderConfiguration = { 
        //Configuration : { 

          //attributes : {
            //token : {tt:ReferenceToken}
          //},
          //Name : { xs:string},
          //UseCount : { xs:int}
        //
        //},
        //ForcePersistence : { xs:boolean}
      //
      //};
      SetAudioEncoderConfiguration : function(args /*, cb, headers*/) {
        throw NOT_IMPLEMENTED;
        //var SetAudioEncoderConfigurationResponse = { };
        //return SetAudioEncoderConfigurationResponse;
      },

      //var SetVideoAnalyticsConfiguration = { 
        //Configuration : { 

          //attributes : {
            //token : {tt:ReferenceToken}
          //},
          //Name : { xs:string},
          //UseCount : { xs:int}
        //
        //},
        //ForcePersistence : { xs:boolean}
      //
      //};
      SetVideoAnalyticsConfiguration : function(args /*, cb, headers*/) {
        throw NOT_IMPLEMENTED;
        //var SetVideoAnalyticsConfigurationResponse = { };
        //return SetVideoAnalyticsConfigurationResponse;
      },

      //var SetMetadataConfiguration = { 
        //Configuration : { 

          //attributes : {
            //token : {tt:ReferenceToken}
          //},
          //Name : { xs:string},
          //UseCount : { xs:int}
        //
        //},
        //ForcePersistence : { xs:boolean}
      //
      //};
      SetMetadataConfiguration : function(args /*, cb, headers*/) {
        throw NOT_IMPLEMENTED;
        //var SetMetadataConfigurationResponse = { };
        //return SetMetadataConfigurationResponse;
      },

      //var SetAudioOutputConfiguration = { 
        //Configuration : { 

          //attributes : {
            //token : {tt:ReferenceToken}
          //},
          //Name : { xs:string},
          //UseCount : { xs:int}
        //
        //},
        //ForcePersistence : { xs:boolean}
      //
      //};
      SetAudioOutputConfiguration : function(args /*, cb, headers*/) {
        throw NOT_IMPLEMENTED;
        //var SetAudioOutputConfigurationResponse = { };
        //return SetAudioOutputConfigurationResponse;
      },

      //var SetAudioDecoderConfiguration = { 
        //Configuration : { 

          //attributes : {
            //token : {tt:ReferenceToken}
          //},
          //Name : { xs:string},
          //UseCount : { xs:int}
        //
        //},
        //ForcePersistence : { xs:boolean}
      //
      //};
      SetAudioDecoderConfiguration : function(args /*, cb, headers*/) {
        throw NOT_IMPLEMENTED;
        //var SetAudioDecoderConfigurationResponse = { };
        //return SetAudioDecoderConfigurationResponse;
      },

      //var GetVideoSourceConfigurationOptions = { 
        //ConfigurationToken : { xs:string},
        //ProfileToken : { xs:string}
      //
      //};
      GetVideoSourceConfigurationOptions : function(args /*, cb, headers*/) {
        throw NOT_IMPLEMENTED;
        //var GetVideoSourceConfigurationOptionsResponse = { 
          //Options : { 
            //BoundsRange : { 
              //XRange : { 
                //Min : { xs:int},
                //Max : { xs:int}
              //},
              //YRange : { 
                //Min : { xs:int},
                //Max : { xs:int}
              //},
              //WidthRange : { 
                //Min : { xs:int},
                //Max : { xs:int}
              //},
              //HeightRange : { 
                //Min : { xs:int},
                //Max : { xs:int}
              //}
            //},
            //VideoSourceTokensAvailable : { xs:string},
            //Extension : { 
              //Rotate : { 
                //Mode : { xs:string},
                //DegreeList : { 
                  //Items : { xs:int}
                //},
                //Extension : { }
              //},
              //Extension : { }
            //}
          //}
        //
        //};
        //return GetVideoSourceConfigurationOptionsResponse;
      },

      //var GetVideoEncoderConfigurationOptions = { 
        //ConfigurationToken : { xs:string},
        //ProfileToken : { xs:string}
      //
      //};
      GetVideoEncoderConfigurationOptions : function(args /*, cb, headers*/) {
        throw NOT_IMPLEMENTED;
        //var GetVideoEncoderConfigurationOptionsResponse = { 
          //Options : { 
            //QualityRange : { 
              //Min : { xs:int},
              //Max : { xs:int}
            //},
            //JPEG : { 
              //ResolutionsAvailable : { 
                //Width : { xs:int},
                //Height : { xs:int}
              //},
              //FrameRateRange : { 
                //Min : { xs:int},
                //Max : { xs:int}
              //},
              //EncodingIntervalRange : { 
                //Min : { xs:int},
                //Max : { xs:int}
              //}
            //},
            //MPEG4 : { 
              //ResolutionsAvailable : { 
                //Width : { xs:int},
                //Height : { xs:int}
              //},
              //GovLengthRange : { 
                //Min : { xs:int},
                //Max : { xs:int}
              //},
              //FrameRateRange : { 
                //Min : { xs:int},
                //Max : { xs:int}
              //},
              //EncodingIntervalRange : { 
                //Min : { xs:int},
                //Max : { xs:int}
              //},
              //Mpeg4ProfilesSupported : { xs:string}
            //},
            //H264 : { 
              //ResolutionsAvailable : { 
                //Width : { xs:int},
                //Height : { xs:int}
              //},
              //GovLengthRange : { 
                //Min : { xs:int},
                //Max : { xs:int}
              //},
              //FrameRateRange : { 
                //Min : { xs:int},
                //Max : { xs:int}
              //},
              //EncodingIntervalRange : { 
                //Min : { xs:int},
                //Max : { xs:int}
              //},
              //H264ProfilesSupported : { xs:string}
            //},
            //Extension : { 
              //JPEG : { 

                //ResolutionsAvailable : { 
                  //Width : { xs:int},
                  //Height : { xs:int}
                //},
                //FrameRateRange : { 
                  //Min : { xs:int},
                  //Max : { xs:int}
                //},
                //EncodingIntervalRange : { 
                  //Min : { xs:int},
                  //Max : { xs:int}
                //}
              //
              //},
              //MPEG4 : { 

                //ResolutionsAvailable : { 
                  //Width : { xs:int},
                  //Height : { xs:int}
                //},
                //GovLengthRange : { 
                  //Min : { xs:int},
                  //Max : { xs:int}
                //},
                //FrameRateRange : { 
                  //Min : { xs:int},
                  //Max : { xs:int}
                //},
                //EncodingIntervalRange : { 
                  //Min : { xs:int},
                  //Max : { xs:int}
                //},
                //Mpeg4ProfilesSupported : { xs:string}
              //
              //},
              //H264 : { 

                //ResolutionsAvailable : { 
                  //Width : { xs:int},
                  //Height : { xs:int}
                //},
                //GovLengthRange : { 
                  //Min : { xs:int},
                  //Max : { xs:int}
                //},
                //FrameRateRange : { 
                  //Min : { xs:int},
                  //Max : { xs:int}
                //},
                //EncodingIntervalRange : { 
                  //Min : { xs:int},
                  //Max : { xs:int}
                //},
                //H264ProfilesSupported : { xs:string}
              //
              //},
              //Extension : { }
            //}
          //}
        //
        //};
        //return GetVideoEncoderConfigurationOptionsResponse;
      },

      //var GetAudioSourceConfigurationOptions = { 
        //ConfigurationToken : { xs:string},
        //ProfileToken : { xs:string}
      //
      //};
      GetAudioSourceConfigurationOptions : function(args /*, cb, headers*/) {
        throw NOT_IMPLEMENTED;
        //var GetAudioSourceConfigurationOptionsResponse = { 
          //Options : { 
            //InputTokensAvailable : { xs:string},
            //Extension : { }
          //}
        //
        //};
        //return GetAudioSourceConfigurationOptionsResponse;
      },

      //var GetAudioEncoderConfigurationOptions = { 
        //ConfigurationToken : { xs:string},
        //ProfileToken : { xs:string}
      //
      //};
      GetAudioEncoderConfigurationOptions : function(args /*, cb, headers*/) {
        throw NOT_IMPLEMENTED;
        //var GetAudioEncoderConfigurationOptionsResponse = { 
          //Options : { 
            //Options : { 
              //Encoding : { xs:string},
              //BitrateList : { 
                //Items : { xs:int}
              //},
              //SampleRateList : { 
                //Items : { xs:int}
              //}
            //}
          //}
        //
        //};
        //return GetAudioEncoderConfigurationOptionsResponse;
      },

      //var GetMetadataConfigurationOptions = { 
        //ConfigurationToken : { xs:string},
        //ProfileToken : { xs:string}
      //
      //};
      GetMetadataConfigurationOptions : function(args /*, cb, headers*/) {
        throw NOT_IMPLEMENTED;
        //var GetMetadataConfigurationOptionsResponse = { 
          //Options : { 
            //PTZStatusFilterOptions : { 
              //PanTiltStatusSupported : { xs:boolean},
              //ZoomStatusSupported : { xs:boolean},
              //PanTiltPositionSupported : { xs:boolean},
              //ZoomPositionSupported : { xs:boolean},
              //Extension : { }
            //},
            //Extension : { 
              //CompressionType : { xs:string},
              //Extension : { }
            //}
          //}
        //
        //};
        //return GetMetadataConfigurationOptionsResponse;
      },

      //var GetAudioOutputConfigurationOptions = { 
        //ConfigurationToken : { xs:string},
        //ProfileToken : { xs:string}
      //
      //};
      GetAudioOutputConfigurationOptions : function(args /*, cb, headers*/) {
        throw NOT_IMPLEMENTED;
        //var GetAudioOutputConfigurationOptionsResponse = { 
          //Options : { 
            //OutputTokensAvailable : { xs:string},
            //SendPrimacyOptions : { xs:anyURI},
            //OutputLevelRange : { 
              //Min : { xs:int},
              //Max : { xs:int}
            //}
          //}
        //
        //};
        //return GetAudioOutputConfigurationOptionsResponse;
      },

      //var GetAudioDecoderConfigurationOptions = { 
        //ConfigurationToken : { xs:string},
        //ProfileToken : { xs:string}
      //
      //};
      GetAudioDecoderConfigurationOptions : function(args /*, cb, headers*/) {
        throw NOT_IMPLEMENTED;
        //var GetAudioDecoderConfigurationOptionsResponse = { 
          //Options : { 
            //AACDecOptions : { 
              //Bitrate : { 
                //Items : { xs:int}
              //},
              //SampleRateRange : { 
                //Items : { xs:int}
              //}
            //},
            //G711DecOptions : { 
              //Bitrate : { 
                //Items : { xs:int}
              //},
              //SampleRateRange : { 
                //Items : { xs:int}
              //}
            //},
            //G726DecOptions : { 
              //Bitrate : { 
                //Items : { xs:int}
              //},
              //SampleRateRange : { 
                //Items : { xs:int}
              //}
            //},
            //Extension : { }
          //}
        //
        //};
        //return GetAudioDecoderConfigurationOptionsResponse;
      },

      //var GetGuaranteedNumberOfVideoEncoderInstances = { 
        //ConfigurationToken : { xs:string}
      //
      //};
      GetGuaranteedNumberOfVideoEncoderInstances : function(args /*, cb, headers*/) {
        throw NOT_IMPLEMENTED;
        //var GetGuaranteedNumberOfVideoEncoderInstancesResponse = { 
          //TotalNumber : { xs:int},
          //JPEG : { xs:int},
          //H264 : { xs:int},
          //MPEG4 : { xs:int}
        //
        //};
        //return GetGuaranteedNumberOfVideoEncoderInstancesResponse;
      },

      //var GetStreamUri = { 
        //StreamSetup : { 
          //Stream : { xs:string}
        //},
        //ProfileToken : { xs:string}
      //
      //};
      GetStreamUri : function(args /*, cb, headers*/) {
        throw NOT_IMPLEMENTED;
        //var GetStreamUriResponse = { 
          //MediaUri : { 
            //Uri : { xs:anyURI},
            //InvalidAfterConnect : { xs:boolean},
            //InvalidAfterReboot : { xs:boolean},
            //Timeout : { xs:duration}
          //}
        //
        //};
        //return GetStreamUriResponse;
      },

      //var StartMulticastStreaming = { 
        //ProfileToken : { xs:string}
      //
      //};
      StartMulticastStreaming : function(args /*, cb, headers*/) {
        throw NOT_IMPLEMENTED;
        //var StartMulticastStreamingResponse = { };
        //return StartMulticastStreamingResponse;
      },

      //var StopMulticastStreaming = { 
        //ProfileToken : { xs:string}
      //
      //};
      StopMulticastStreaming : function(args /*, cb, headers*/) {
        throw NOT_IMPLEMENTED;
        //var StopMulticastStreamingResponse = { };
        //return StopMulticastStreamingResponse;
      },

      //var SetSynchronizationPoint = { 
        //ProfileToken : { xs:string}
      //
      //};
      SetSynchronizationPoint : function(args /*, cb, headers*/) {
        throw NOT_IMPLEMENTED;
        //var SetSynchronizationPointResponse = { };
        //return SetSynchronizationPointResponse;
      },

      //var GetSnapshotUri = { 
        //ProfileToken : { xs:string}
      //
      //};
      GetSnapshotUri : function(args /*, cb, headers*/) {
        throw NOT_IMPLEMENTED;
        //var GetSnapshotUriResponse = { 
          //MediaUri : { 
            //Uri : { xs:anyURI},
            //InvalidAfterConnect : { xs:boolean},
            //InvalidAfterReboot : { xs:boolean},
            //Timeout : { xs:duration}
          //}
        //
        //};
        //return GetSnapshotUriResponse;
      },

      //var GetVideoSourceModes = { 
        //VideoSourceToken : { xs:string}
      //
      //};
      GetVideoSourceModes : function(args /*, cb, headers*/) {
        throw NOT_IMPLEMENTED;
        //var GetVideoSourceModesResponse = { 
          //VideoSourceModes : { 
            //attributes : {
              //token : {tt:ReferenceToken},
              //Enabled : {xs:boolean}
            //},
            //MaxFramerate : { xs:float},
            //MaxResolution : { 
              //Width : { xs:int},
              //Height : { xs:int}
            //},
            //Encodings : { simpleType},
            //Reboot : { xs:boolean},
            //Description : { xs:string},
            //Extension : { }
          //}
        //
        //};
        //return GetVideoSourceModesResponse;
      },

      //var SetVideoSourceMode = { 
        //VideoSourceToken : { xs:string},
        //VideoSourceModeToken : { xs:string}
      //
      //};
      SetVideoSourceMode : function(args /*, cb, headers*/) {
        throw NOT_IMPLEMENTED;
        //var SetVideoSourceModeResponse = { 
          //Reboot : { xs:boolean}
        //
        //};
        //return SetVideoSourceModeResponse;
      },

      //var GetOSDs = { 
        //ConfigurationToken : { xs:string}
      //
      //};
      GetOSDs : function(args /*, cb, headers*/) {
        throw NOT_IMPLEMENTED;
        //var GetOSDsResponse = { 
          //OSDs : { 

            //attributes : {
              //token : {tt:ReferenceToken}
            //}
          //}
        //
        //};
        //return GetOSDsResponse;
      },

      //var GetOSD = { 
        //OSDToken : { xs:string}
      //
      //};
      GetOSD : function(args /*, cb, headers*/) {
        throw NOT_IMPLEMENTED;
        //var GetOSDResponse = { 
          //OSD : { 

            //attributes : {
              //token : {tt:ReferenceToken}
            //}
          //}
        //
        //};
        //return GetOSDResponse;
      },

      //var GetOSDOptions = { 
        //ConfigurationToken : { xs:string}
      //
      //};
      GetOSDOptions : function(args /*, cb, headers*/) {
        throw NOT_IMPLEMENTED;
        //var GetOSDOptionsResponse = { 
          //OSDOptions : { 
            //MaximumNumberOfOSDs : { 
              //attributes : {
                //Total : {xs:int},
                //Image : {xs:int},
                //PlainText : {xs:int},
                //Date : {xs:int},
                //Time : {xs:int},
                //DateAndTime : {xs:int}
              //}},
            //Type : { xs:string},
            //PositionOption : { xs:string},
            //TextOption : { 
              //Type : { xs:string},
              //FontSizeRange : { 
                //Min : { xs:int},
                //Max : { xs:int}
              //},
              //DateFormat : { xs:string},
              //TimeFormat : { xs:string},
              //FontColor : { 
                //Color : { },
                //Transparent : { 
                  //Min : { xs:int},
                  //Max : { xs:int}
                //},
                //Extension : { }
              //},
              //BackgroundColor : { 
                //Color : { },
                //Transparent : { 
                  //Min : { xs:int},
                  //Max : { xs:int}
                //},
                //Extension : { }
              //},
              //Extension : { }
            //},
            //ImageOption : { 
              //ImagePath : { xs:anyURI},
              //Extension : { }
            //},
            //Extension : { }
          //}
        //
        //};
        //return GetOSDOptionsResponse;
      },

      //var SetOSD = { 
        //OSD : { 

          //attributes : {
            //token : {tt:ReferenceToken}
          //}
        //}
      //
      //};
      SetOSD : function(args /*, cb, headers*/) {
        throw NOT_IMPLEMENTED;
        //var SetOSDResponse = { };
        //return SetOSDResponse;
      },

      //var CreateOSD = { 
        //OSD : { 

          //attributes : {
            //token : {tt:ReferenceToken}
          //}
        //}
      //
      //};
      CreateOSD : function(args /*, cb, headers*/) {
        throw NOT_IMPLEMENTED;
        //var CreateOSDResponse = { 
          //OSDToken : { xs:string}
        //
        //};
        //return CreateOSDResponse;
      },

      //var DeleteOSD = { 
        //OSDToken : { xs:string}
      //
      //};
      DeleteOSD : function(args /*, cb, headers*/) {
        throw NOT_IMPLEMENTED;
        //var DeleteOSDResponse = { };
        //return DeleteOSDResponse;
      },

    }
  }
}
